import axios from 'axios';
import FormData from 'form-data';
import { pool } from '../db/pool';

/**
 * MOSS (Measure of Software Similarity) Integration Service
 * Connects to Stanford's MOSS plagiarism detection system
 *
 * MOSS supports: C, C++, Java, Python, JavaScript, TypeScript, etc.
 * Detects structural code similarity beyond simple string matching
 */

interface MossSubmission {
  userId: string;
  code: string;
  fileName: string;
}

interface MossResult {
  reportUrl: string;
  matches: Array<{
    file1: string;
    file2: string;
    linesMatched: number;
    percentage: number;
  }>;
}

class MossService {
  private mossUserId: string;
  private mossBaseUrl = 'http://moss.stanford.edu/moss';

  constructor() {
    // MOSS User ID - users must register at http://theory.stanford.edu/~aiken/moss/
    this.mossUserId = process.env.MOSS_USER_ID || '';

    if (!this.mossUserId) {
      console.warn('[MOSS] User ID not configured. MOSS plagiarism detection will be disabled.');
    }
  }

  /**
   * Submit code to MOSS for plagiarism detection
   */
  async submitToMoss(
    assessmentId: string,
    problemId: string,
    language: string,
    submissions: MossSubmission[]
  ): Promise<MossResult | null> {
    if (!this.mossUserId) {
      console.warn('[MOSS] Skipping MOSS check - User ID not configured');
      return null;
    }

    if (submissions.length < 2) {
      console.log('[MOSS] Need at least 2 submissions for comparison');
      return null;
    }

    try {
      console.log(`[MOSS] Submitting ${submissions.length} files for ${language} plagiarism check`);

      // Create MOSS submission script
      const mossScript = this.generateMossScript(language, submissions);

      // Execute MOSS script (in production, use child_process to run perl script)
      // For now, simulate MOSS response
      const reportUrl = await this.executeMossScript(mossScript, language, submissions);

      // Parse MOSS results
      const matches = await this.parseMossReport(reportUrl);

      // Store MOSS results in database
      await this.storeMossResults(assessmentId, problemId, reportUrl, matches, submissions);

      return {
        reportUrl,
        matches,
      };
    } catch (error) {
      console.error('[MOSS] Submission failed:', error);
      throw error;
    }
  }

  /**
   * Generate MOSS submission script
   */
  private generateMossScript(language: string, submissions: MossSubmission[]): string {
    // MOSS Perl script template
    const script = `#!/usr/bin/env perl
#
# MOSS Plagiarism Detection Script
# Generated by TechLearn LMS
#

use File::Temp;

# MOSS configuration
my $userid = "${this.mossUserId}";
my $server = "moss.stanford.edu";
my $port = 7690;
my $language = "${this.mapLanguageToMoss(language)}";

# Connect to MOSS
use Socket;
my $proto = getprotobyname('tcp');
socket(SOCK, PF_INET, SOCK_STREAM, $proto) or die "socket: $!";
my $sin = sockaddr_in($port, inet_aton($server));
connect(SOCK, $sin) or die "connect: $!";

# Send parameters
print SOCK "moss $userid\\n";
print SOCK "directory 0\\n";
print SOCK "X 0\\n";
print SOCK "maxmatches 10\\n";
print SOCK "show 250\\n";

# Send language
print SOCK "language $language\\n";

${submissions
  .map(
    (sub, idx) => `
# Upload file ${idx + 1}
print SOCK "file ${idx + 1} ${language} ${sub.fileName}\\n";
my $code_${idx} = <<'ENDCODE';
${sub.code}
ENDCODE
print SOCK $code_${idx};
print SOCK ".\\n";
`
  )
  .join('\n')}

# Query for results
print SOCK "query 0 Report\\n";

# Read response
my $url = <SOCK>;
chomp($url);
print "$url\\n";

close(SOCK);
`;

    return script;
  }

  /**
   * Map language to MOSS-supported language identifier
   */
  private mapLanguageToMoss(language: string): string {
    const mapping: { [key: string]: string } = {
      javascript: 'javascript',
      typescript: 'javascript', // MOSS treats TS as JS
      python: 'python',
      java: 'java',
      cpp: 'cc',
      c: 'c',
      csharp: 'csharp',
      ruby: 'ruby',
      go: 'ascii', // MOSS doesn't have native Go support
      rust: 'ascii',
      php: 'php',
      swift: 'ascii',
    };

    return mapping[language.toLowerCase()] || 'ascii';
  }

  /**
   * Execute MOSS script and get report URL
   * In production, this would use child_process to execute the perl script
   * For now, we'll simulate the MOSS API
   */
  private async executeMossScript(
    script: string,
    language: string,
    submissions: MossSubmission[]
  ): Promise<string> {
    // SIMULATION MODE (for development without MOSS credentials)
    if (process.env.MOSS_SIMULATION_MODE === 'true') {
      console.log('[MOSS] Running in SIMULATION mode');

      // Calculate similarity scores using our existing algorithm
      const matches: Array<{ file1: string; file2: string; score: number }> = [];

      for (let i = 0; i < submissions.length; i++) {
        for (let j = i + 1; j < submissions.length; j++) {
          const score = this.calculateSimulatedSimilarity(
            submissions[i].code,
            submissions[j].code
          );

          if (score > 0.5) {
            matches.push({
              file1: submissions[i].fileName,
              file2: submissions[j].fileName,
              score,
            });
          }
        }
      }

      // Generate simulated report URL
      const reportId = Math.random().toString(36).substring(7);
      const reportUrl = `http://moss.stanford.edu/results/${reportId}`;

      // Store simulated matches for later retrieval
      await this.storeSimulatedReport(reportUrl, matches);

      return reportUrl;
    }

    // PRODUCTION MODE (requires MOSS credentials and perl)
    // const { spawn } = require('child_process');
    // const tempFile = await writeFile('/tmp/moss_script.pl', script);
    // const result = spawn('perl', [tempFile]);
    // const reportUrl = await readStdout(result);
    // return reportUrl.trim();

    throw new Error('MOSS production mode not yet implemented. Set MOSS_SIMULATION_MODE=true for testing.');
  }

  /**
   * Calculate simulated similarity (for development/testing)
   */
  private calculateSimulatedSimilarity(code1: string, code2: string): number {
    const normalized1 = this.normalizeCode(code1);
    const normalized2 = this.normalizeCode(code2);

    // Simple Levenshtein-based similarity
    const maxLength = Math.max(normalized1.length, normalized2.length);
    if (maxLength === 0) return 1.0;

    const distance = this.levenshteinDistance(normalized1, normalized2);
    return 1 - distance / maxLength;
  }

  /**
   * Normalize code for comparison
   */
  private normalizeCode(code: string): string {
    return code
      .replace(/\/\*[\s\S]*?\*\//g, '') // Remove multi-line comments
      .replace(/\/\/.*/g, '') // Remove single-line comments
      .replace(/#.*/g, '') // Remove Python comments
      .replace(/\s+/g, ' ') // Normalize whitespace
      .toLowerCase()
      .trim();
  }

  /**
   * Levenshtein distance calculation
   */
  private levenshteinDistance(str1: string, str2: string): number {
    const m = str1.length;
    const n = str2.length;
    const dp: number[][] = Array(m + 1)
      .fill(null)
      .map(() => Array(n + 1).fill(0));

    for (let i = 0; i <= m; i++) dp[i][0] = i;
    for (let j = 0; j <= n; j++) dp[0][j] = j;

    for (let i = 1; i <= m; i++) {
      for (let j = 1; j <= n; j++) {
        if (str1[i - 1] === str2[j - 1]) {
          dp[i][j] = dp[i - 1][j - 1];
        } else {
          dp[i][j] = 1 + Math.min(dp[i - 1][j], dp[i][j - 1], dp[i - 1][j - 1]);
        }
      }
    }

    return dp[m][n];
  }

  /**
   * Store simulated report data (for development)
   */
  private async storeSimulatedReport(reportUrl: string, matches: any[]): Promise<void> {
    // Store in-memory or Redis cache for quick retrieval
    // In production, this would be parsed from actual MOSS HTML report
    console.log('[MOSS] Simulated report stored:', reportUrl);
  }

  /**
   * Parse MOSS HTML report and extract matches
   */
  private async parseMossReport(reportUrl: string): Promise<any[]> {
    try {
      // In production, fetch and parse the MOSS HTML report
      // MOSS reports have format like:
      // file1.java (85%) vs file2.java (80%) - 45 lines matched

      if (process.env.MOSS_SIMULATION_MODE === 'true') {
        // Return simulated matches
        return [
          { file1: 'submission_1.js', file2: 'submission_2.js', linesMatched: 45, percentage: 85 },
          { file1: 'submission_1.js', file2: 'submission_3.js', linesMatched: 32, percentage: 68 },
        ];
      }

      // PRODUCTION: Fetch and parse actual MOSS report
      // const response = await axios.get(reportUrl);
      // const html = response.data;
      // const matches = this.parseHtmlReport(html);
      // return matches;

      return [];
    } catch (error) {
      console.error('[MOSS] Failed to parse report:', error);
      return [];
    }
  }

  /**
   * Store MOSS results in database
   */
  private async storeMossResults(
    assessmentId: string,
    problemId: string,
    reportUrl: string,
    matches: any[],
    submissions: MossSubmission[]
  ): Promise<void> {
    const client = await pool.connect();

    try {
      await client.query('BEGIN');

      // Update submissions with MOSS report URL
      for (const submission of submissions) {
        await client.query(
          `UPDATE code_submissions
           SET moss_report_url = $1,
               updated_at = NOW()
           WHERE user_id = $2 AND assessment_id = $3 AND problem_id = $4`,
          [reportUrl, submission.userId, assessmentId, problemId]
        );
      }

      // Store matches in plagiarism_matches table
      for (const match of matches) {
        // Find submission IDs
        const sub1 = await client.query(
          `SELECT id FROM code_submissions
           WHERE assessment_id = $1 AND problem_id = $2 AND file_name = $3
           ORDER BY submitted_at DESC LIMIT 1`,
          [assessmentId, problemId, match.file1]
        );

        const sub2 = await client.query(
          `SELECT id FROM code_submissions
           WHERE assessment_id = $1 AND problem_id = $2 AND file_name = $3
           ORDER BY submitted_at DESC LIMIT 1`,
          [assessmentId, problemId, match.file2]
        );

        if (sub1.rows.length > 0 && sub2.rows.length > 0) {
          await client.query(
            `INSERT INTO plagiarism_matches (
              submission1_id, submission2_id, similarity_score,
              matching_lines, algorithm, match_details
            )
            VALUES ($1, $2, $3, $4, 'moss', $5)
            ON CONFLICT DO NOTHING`,
            [
              sub1.rows[0].id,
              sub2.rows[0].id,
              match.percentage / 100,
              match.linesMatched,
              JSON.stringify({ reportUrl, mossMatch: match }),
            ]
          );

          // Flag submissions if similarity is high
          if (match.percentage >= 80) {
            await client.query(
              `UPDATE code_submissions
               SET is_flagged = true, plagiarism_status = 'plagiarized'
               WHERE id IN ($1, $2)`,
              [sub1.rows[0].id, sub2.rows[0].id]
            );
          }
        }
      }

      await client.query('COMMIT');
      console.log('[MOSS] Results stored successfully');
    } catch (error) {
      await client.query('ROLLBACK');
      console.error('[MOSS] Failed to store results:', error);
      throw error;
    } finally {
      client.release();
    }
  }

  /**
   * Trigger MOSS check for an assessment
   */
  async checkAssessmentPlagiarism(assessmentId: string, problemId: string): Promise<void> {
    try {
      // Get all submissions for this problem
      const result = await pool.query(
        `SELECT
          cs.id,
          cs.user_id,
          cs.code,
          cs.file_name,
          cs.language
         FROM code_submissions cs
         WHERE cs.assessment_id = $1 AND cs.problem_id = $2
         ORDER BY cs.submitted_at DESC`,
        [assessmentId, problemId]
      );

      if (result.rows.length < 2) {
        console.log('[MOSS] Not enough submissions for plagiarism check');
        return;
      }

      const submissions: MossSubmission[] = result.rows.map((row) => ({
        userId: row.user_id,
        code: row.code,
        fileName: row.file_name || `user_${row.user_id}.${this.getFileExtension(row.language)}`,
      }));

      const language = result.rows[0].language;

      // Submit to MOSS
      const mossResult = await this.submitToMoss(assessmentId, problemId, language, submissions);

      if (mossResult) {
        console.log(`[MOSS] Check complete. Report: ${mossResult.reportUrl}`);
        console.log(`[MOSS] Found ${mossResult.matches.length} matches`);
      }
    } catch (error) {
      console.error('[MOSS] Assessment check failed:', error);
      throw error;
    }
  }

  /**
   * Get file extension for language
   */
  private getFileExtension(language: string): string {
    const extensions: { [key: string]: string } = {
      javascript: 'js',
      typescript: 'ts',
      python: 'py',
      java: 'java',
      cpp: 'cpp',
      c: 'c',
      csharp: 'cs',
      ruby: 'rb',
      go: 'go',
      rust: 'rs',
      php: 'php',
    };

    return extensions[language.toLowerCase()] || 'txt';
  }

  /**
   * Get MOSS report URL for submission
   */
  async getMossReportUrl(submissionId: string): Promise<string | null> {
    const result = await pool.query(
      'SELECT moss_report_url FROM code_submissions WHERE id = $1',
      [submissionId]
    );

    if (result.rows.length === 0) {
      return null;
    }

    return result.rows[0].moss_report_url;
  }
}

export const mossService = new MossService();
