import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Routes, Route, Navigate } from "react-router-dom";
import ProtectedRoute from "./components/auth/ProtectedRoute";
import LoginPage from "./pages/auth/LoginPage";
import RegisterPage from "./pages/auth/RegisterPage";
import OAuthCallback from "./pages/auth/OAuthCallback";
import ForgotPasswordPage from "./pages/auth/ForgotPasswordPage";
import ResetPasswordPage from "./pages/auth/ResetPasswordPage";
import VerifyEmailPage from "./pages/auth/VerifyEmailPage";
import StudentDashboard from "./pages/student/StudentDashboard";
import InstructorDashboard from "./pages/instructor/InstructorDashboard";
import AdminDashboard from "./pages/admin/AdminDashboard";
import CourseCatalog from "./pages/courses/CourseCatalog";
import CourseDetail from "./pages/courses/CourseDetail";
import LessonViewer from "./pages/courses/LessonViewer";
import MyCourses from "./pages/instructor/MyCourses";
import CourseEditor from "./pages/instructor/CourseEditor";
import { AITutorPage } from "./pages/ai-tutor/AITutorPage";
import { PeerReviewPage } from "./pages/peer-review/PeerReviewPage";
import StudentHealthPage from "./pages/health/StudentHealthPage";
import InstructorHealthPage from "./pages/health/InstructorHealthPage";
import IntegrityDashboardPage from "./pages/integrity/IntegrityDashboardPage";
import ProfilePage from "./pages/profile/ProfilePage";
import SettingsPage from "./pages/settings/SettingsPage";
import LeaderboardPage from "./pages/community/LeaderboardPage";
import ForumPage from "./pages/community/ForumPage";
import PricingPage from "./pages/billing/PricingPage";
import LiveClassesPage from "./pages/courses/LiveClassesPage";
import StudyGroupsPage from "./pages/community/StudyGroupsPage";
import PortfolioPage from "./pages/portfolio/PortfolioPage";
import CareerOutcomesPage from "./pages/career/CareerOutcomesPage";
import AdaptiveLearningPage from "./pages/admin/AdaptiveLearningPage";
import VivaAssessmentPage from "./pages/assessment/VivaAssessmentPage";
import AdminDashboardEnhanced from "./pages/admin/AdminDashboard.Enhanced";
import MessagingPage from "./pages/messaging/MessagingPage";
import PaymentForm from "./components/billing/PaymentForm";
import GDPRCompliancePage from "./pages/privacy/GDPRCompliancePage";
import IDEEditorPage from "./pages/ide/IDEEditorPage";
import CertificationGalleryPage from "./pages/certification/CertificationGalleryPage";
import BlockchainCertificateViewerPage from "./pages/certification/BlockchainCertificateViewerPage";
import AdvancedSearchPage from "./pages/search/AdvancedSearchPage";
import OrganizationBrandingPage from "./pages/admin/OrganizationBrandingPage";
const NotFound = () => (_jsx("div", { style: { padding: "2rem", textAlign: "center" }, children: _jsx("h1", { children: "404 \u2014 Page not found" }) }));
export default function App() {
    return (_jsxs(Routes, { children: [_jsx(Route, { path: "/login", element: _jsx(LoginPage, {}) }), _jsx(Route, { path: "/register", element: _jsx(RegisterPage, {}) }), _jsx(Route, { path: "/forgot-password", element: _jsx(ForgotPasswordPage, {}) }), _jsx(Route, { path: "/reset-password", element: _jsx(ResetPasswordPage, {}) }), _jsx(Route, { path: "/verify-email", element: _jsx(VerifyEmailPage, {}) }), _jsx(Route, { path: "/auth/callback", element: _jsx(OAuthCallback, {}) }), _jsx(Route, { path: "/courses", element: _jsx(CourseCatalog, {}) }), _jsx(Route, { path: "/courses/:id", element: _jsx(CourseDetail, {}) }), _jsx(Route, { path: "/pricing", element: _jsx(PricingPage, {}) }), _jsx(Route, { path: "/privacy", element: _jsx(GDPRCompliancePage, {}) }), _jsx(Route, { path: "/search", element: _jsx(AdvancedSearchPage, {}) }), _jsxs(Route, { element: _jsx(ProtectedRoute, { allowedRoles: ["student"] }), children: [_jsx(Route, { path: "/dashboard", element: _jsx(StudentDashboard, {}) }), _jsx(Route, { path: "/courses/:courseId/learn", element: _jsx(LessonViewer, {}) }), _jsx(Route, { path: "/ai-tutor", element: _jsx(AITutorPage, {}) }), _jsx(Route, { path: "/peer-review", element: _jsx(PeerReviewPage, {}) }), _jsx(Route, { path: "/health/:courseId", element: _jsx(StudentHealthPage, {}) }), _jsx(Route, { path: "/profile", element: _jsx(ProfilePage, {}) }), _jsx(Route, { path: "/settings", element: _jsx(SettingsPage, {}) }), _jsx(Route, { path: "/leaderboard", element: _jsx(LeaderboardPage, {}) }), _jsx(Route, { path: "/forum", element: _jsx(ForumPage, {}) }), _jsx(Route, { path: "/live-classes", element: _jsx(LiveClassesPage, {}) }), _jsx(Route, { path: "/study-groups", element: _jsx(StudyGroupsPage, {}) }), _jsx(Route, { path: "/portfolio", element: _jsx(PortfolioPage, {}) }), _jsx(Route, { path: "/career-outcomes", element: _jsx(CareerOutcomesPage, {}) }), _jsx(Route, { path: "/adaptive-learning", element: _jsx(AdaptiveLearningPage, {}) }), _jsx(Route, { path: "/viva-assessment", element: _jsx(VivaAssessmentPage, {}) }), _jsx(Route, { path: "/messages", element: _jsx(MessagingPage, {}) }), _jsx(Route, { path: "/checkout", element: _jsx(PaymentForm, {}) }), _jsx(Route, { path: "/ide-editor", element: _jsx(IDEEditorPage, {}) }), _jsx(Route, { path: "/certifications", element: _jsx(CertificationGalleryPage, {}) }), _jsx(Route, { path: "/blockchain-certificates", element: _jsx(BlockchainCertificateViewerPage, {}) })] }), _jsxs(Route, { element: _jsx(ProtectedRoute, { allowedRoles: ["instructor"] }), children: [_jsx(Route, { path: "/instructor/dashboard", element: _jsx(InstructorDashboard, {}) }), _jsx(Route, { path: "/instructor/courses", element: _jsx(MyCourses, {}) }), _jsx(Route, { path: "/instructor/courses/:id/edit", element: _jsx(CourseEditor, {}) }), _jsx(Route, { path: "/instructor/health/:courseId", element: _jsx(InstructorHealthPage, {}) }), _jsx(Route, { path: "/instructor/integrity", element: _jsx(IntegrityDashboardPage, {}) }), _jsx(Route, { path: "/instructor/integrity/:assessmentId", element: _jsx(IntegrityDashboardPage, {}) }), _jsx(Route, { path: "/instructor/live-classes", element: _jsx(LiveClassesPage, {}) }), _jsx(Route, { path: "/instructor/messages", element: _jsx(MessagingPage, {}) })] }), _jsxs(Route, { element: _jsx(ProtectedRoute, { allowedRoles: ["admin"] }), children: [_jsx(Route, { path: "/admin/dashboard", element: _jsx(AdminDashboard, {}) }), _jsx(Route, { path: "/admin/dashboard-enhanced", element: _jsx(AdminDashboardEnhanced, {}) }), _jsx(Route, { path: "/admin/adaptive-learning", element: _jsx(AdaptiveLearningPage, {}) }), _jsx(Route, { path: "/admin/messages", element: _jsx(MessagingPage, {}) }), _jsx(Route, { path: "/admin/branding", element: _jsx(OrganizationBrandingPage, {}) })] }), _jsx(Route, { path: "/", element: _jsx(Navigate, { to: "/login", replace: true }) }), _jsx(Route, { path: "*", element: _jsx(NotFound, {}) })] }));
}
